# Generated by Django 2.2.3 on 2019-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='genres', to='myblog.Post'),
        ),
    ]
